### ISSUE TITLE
VIPM Install Issues

### ISSUE THREAD

**Issue by jyoung8711** [illuminated-g/lv-ide-snippets#2]
It seems there's an issue with the Post Install step in the VIPM package.  End up with an error 1003 during the install, for the inability to Run the "PostInstall.vi".  During the actual install process it seems to be looking for a VI named "Install LVClassLibrary Tools.vi" 

Not sure if there's a dependency issue, or something else going on.

**Comment by negentropicdev** [comment]
@jyoung8711 Let me take a look!

**Comment by negentropicdev** [comment]
Seeing the issue in my 2021 VM, learnin me some lessons about VIPM packaging, have a fix for you posted here in a jiffy

**Comment by negentropicdev** [comment]
@jyoung8711 For now you can download the .vip from the 1.0.1.14 release at https://github.com/illuminated-g/lv-ide-snippets/releases/tag/1.0.1.14

Update has been submitted to vipm.io

**Comment by negentropicdev** [comment]
It's now available directly from VIPM as well.

**Comment by jyoung8711** [comment]
Thanks! Looking forward to trying it out.
